# Generated by Django 3.1.7 on 2021-04-08 07:03

from django.db import migrations, models
import django_app.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210404_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('passwd', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=django_app.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
