# Generated by Django 3.1.7 on 2021-04-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_member_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='passwd',
        ),
    ]
