# Generated by Django 3.1.7 on 2021-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210411_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pozitivita',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
