# Generated by Django 3.1.7 on 2021-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_member_pozitivita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pozitivita',
            field=models.CharField(max_length=100),
        ),
    ]
